### ISSUE TITLE
[minor] Prefixing helper classes

### ISSUE THREAD

**Issue by misscs** [CasperSleep/nightshade-core#23]
## The Problem

```
<a class="-light" href="/">
```

> Off topic, no changes needed: I like the -something naming scheme a lot for modifiers to an existing class. I think it looks kind of weird as a standalone though. What do you think about a universal prefix for all helper classes?

[From @robwierzbowski ](https://github.com/CasperSleep/nightshade-core/commit/48cea1e0eafdb5b4f3cdf270e84518fc925a2d2f#commitcomment-16211136)
## Goals
- Do we want to prefix helper classes?
- What prefix do we want to use? 
- Do we need helper classes? If so, do we need all the ones we have currently defined?

**Comment by robwierzbowski** [comment]
I love using `-foo` classes as modifiers in a semantic module, because it looks like a SMACSS/BEM modifier but is much shorter, (e.g., `.hero.-video`, `.notification.-error`). But for me, modifier classes are always scoped to a class that they're modifying, and never exist on their own:

``` scss
.notification {
  // bunch of styles
  &.-error {
    color: color(red);
    background: color(dark-red);

    a {
      color: color(red);
    }
  }
}
```

If we're not sure we need helper classes, let's start out with mixins. Eventually these mixins could be packaged in a helper class when we decide we want to expose it for composition in HTML. Maybe we can give the helper classes a single letter prefix to differentiate them from anything else.

Example:

``` scss
// Used in various semantic or presentation modules
@mixin light-text() {
  font-weight: 300;
}

// Once we decide that we would like to expose on its own
.C-light-text { // C for Casper!
  @include light-text();
}
```

I think it could also be helpful to have some guidelines for what can be in a helper class, or how to use. Do we use helper classes in our presentation modules, or keep all of the styles packaged in a single-class-per-element structure? Can we pile on top of each other? If so, what do we allow in a helper to avoid side effects (based on source order, for example).

_I'm sure you've thought about a lot of these things already._
